Repository WPMedia/arc-themes-components, pull requests merged in 2022-10, with the labels that each got.

#144 TMEDIA 851 badge color update
  .storybook/themes/commerce.scss
Labels: ready for review

#146 TBRANDS-106 & TBRANDS-126 : Product Gallery Desktop View
  src/components/image/index.jsx
Labels: WIP

#147 TMEDIA-839: Add usePhrases() hook
  .eslintrc.js
  .storybook/alias/context.js
  .storybook/alias/intl.js
  .storybook/alias/properties.js
  .storybook/main.js
  babel.config.js
  index.js
  jest/mocks/context.js
  jest/mocks/intl.js
  jest/mocks/properties.js
  package-lock.json
  package.json
  src/utils/hooks/use-phrases/index.js
  src/utils/hooks/use-phrases/index.stories.mdx
  src/utils/hooks/use-phrases/index.test.js
Labels: ready for review

#148 Fix null values and result hash structure
  src/utils/sign-images-in-ans-object/index.js
  src/utils/sign-images-in-ans-object/index.test.js
Labels: ready to merge
