Repository WPMedia/arc-themes-components, pull requests merged in 2022-04, with the labels that each got.

#57 TMEDIA-773 - Carousel Component without Library
  .babelrc
  index.js
  package-lock.json
  package.json
  resources/camera.jpeg
  resources/canyon.jpeg
  resources/coffee.jpeg
  scss.scss
  src/components/carousel/_children/Button.jsx
  src/components/carousel/_children/Item.jsx
  src/components/carousel/_children/Item.test.jsx
  src/components/carousel/_index.scss
  src/components/carousel/index.jsx
  src/components/carousel/index.stories.mdx
  src/components/carousel/index.test.jsx
  src/components/icon/index.jsx
Labels: ready to merge

#63 TMEDIA-778 - Allow components to not need a default value set within components map
  .stylelintrc.json
  src/scss/index.test.scss
  src/scss/root/_index.scss
Labels: ready for review

#65 Carousel - Fix issue where next button shows when there is no more items
  .github/workflows/pull-requests-test-and-lint.yml
  src/components/carousel/index.jsx
  src/components/carousel/index.stories.mdx
  src/components/carousel/index.test.jsx
Labels: ready to merge

#68 Add break-word to carousel component as default
  src/components/carousel/_index.scss
Labels: ready for review

#69 Carousel - Reduce duplication of button generation
  src/components/carousel/index.jsx
Labels: ready for review

#66 TMEDIA-684 - Grid Component
  index.js
  scss.scss
  src/components/grid/_index.scss
  src/components/grid/index.jsx
  src/components/grid/index.stories.mdx
  src/components/grid/index.test.jsx
Labels: ready for review

#64 TMEDIA-834 full screen carousel (off of tmedia 689)
  src/components/carousel/_index.scss
  src/components/carousel/index.jsx
  src/components/carousel/index.stories.mdx
  src/components/carousel/index.test.jsx
Labels: ready for review

#70 chore: Add license based on existing licensing decisions
  LICENSE.md
Labels: ready for review

#71 Tmedia 836 label counter
  .storybook/themes/commerce.scss
  src/components/carousel/_index.scss
  src/components/carousel/index.jsx
  src/components/carousel/index.stories.mdx
  src/components/carousel/index.test.jsx
Labels: additional review, ready for review

#72 Chore remove stylelint ie 10
  .browserslistrc
  .stylelintrc.json
  package-lock.json
Labels: POC

#75 Carousel slides to view per breakpoint
  .storybook/themes/news.scss
  src/components/carousel/_index.scss
  src/components/carousel/index.jsx
  src/components/carousel/index.test.jsx
Labels: ready for review

#76 Carousel - Adjust pointer events for carousel actions to allow swiping over area
  .stylelintrc.json
  src/components/carousel/_index.scss
  src/components/carousel/index.jsx
  src/components/carousel/index.stories.mdx
Labels: ready for review

#77 Heading - Add truncation
  src/components/headings/_index.scss
  src/components/headings/heading/index.jsx
  src/components/headings/index.stories.mdx
  src/components/headings/index.test.jsx
  src/components/paragraph/_index.scss
Labels: ready to merge

#73 tmedia 689 autoplay carousel
  index.js
  src/components/carousel/_index.scss
  src/components/carousel/index.jsx
  src/components/carousel/index.stories.mdx
  src/components/carousel/index.test.jsx
  src/utils/is-server-side/isServerSide.js
  src/utils/is-server-side/isServerSide.test.js
  src/utils/use-interval/useInterval.js
Labels: ready to merge

#79 Carousel width fixes
  src/components/carousel/_index.scss
  src/components/carousel/index.jsx
Labels: ready to merge

#80 Ad Ad props and update rendering logic
  src/components/carousel/index.jsx
  src/components/carousel/index.stories.mdx
  src/components/carousel/index.test.jsx
Labels: ready to merge

#81 New Component - Price
  index.js
  scss.scss
  src/components/price/_children/List.jsx
  src/components/price/_children/Sale.jsx
  src/components/price/_index.scss
  src/components/price/index.jsx
  src/components/price/index.stories.mdx
  src/components/price/index.test.jsx
Labels: ready to merge

#83 File Naming Update
  index.js
  src/components/carousel/index.jsx
  src/utils/format-credits/index.test.js
  src/utils/format-powa-video-embed/index.test.js
  src/utils/hooks/use-interval/index.js
  src/utils/is-server-side/index.js
  src/utils/is-server-side/index.test.js
Labels: ready for review

#85 Ensure Children component order is maintained
  src/components/price/index.jsx
  src/components/price/index.test.jsx
Labels: ready for review
