Repository WPMedia/arc-themes-components, pull requests merged in 2022-02, with the labels that each got.

#24 Tmedia 660 prettier ticket
  .babelrc
  .eslintignore
  .eslintrc.js
  .github/workflows/beta-publish.yml
  .github/workflows/canary-publish.yml
  .github/workflows/chromatic.yml
  .github/workflows/rc-publish.yml
  .github/workflows/stable-publish.yml
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  .storybook/theme.js
  .storybook/theme.scss
  .stylelintrc.json
  .vscode/extensions.json
  .vscode/settings.json
  __tests__/scss.test.js
  _templates/component/new/prompt.js
  index.js
  jest.config.js
  jest/fileTransformer.js
  jest/testSetupFile.js
  package-lock.json
  package.json
  scss.scss
  src/components/headings/_index.scss
  src/components/headings/context.js
  src/components/headings/heading/index.jsx
  src/components/headings/index.stories.mdx
  src/components/headings/index.test.jsx
  src/components/headings/section/index.jsx
  src/components/link/_index.scss
  src/components/link/index.jsx
  src/components/link/index.stories.mdx
  src/components/link/index.test.jsx
  src/components/paragraph/index.jsx
  src/components/paragraph/index.stories.mdx
  src/components/paragraph/index.test.jsx
  src/scss/index.scss
  src/scss/index.test.scss
  src/scss/root/_index.scss
  src/scss/root/_reset.scss
Labels: additional review, ready for review

#27 LINTING improvement: Update linting to enforce new jsx runtime
  .eslintrc.js
  src/components/paragraph/index.jsx
  src/components/paragraph/index.test.jsx
Labels: ready for review

#26 Refactor additionalClassnames to use className
  _templates/component/new/default-entry.ejs.t
  src/components/headings/heading/index.jsx
  src/components/headings/index.stories.mdx
  src/components/headings/index.test.jsx
  src/components/link/index.jsx
  src/components/link/index.test.jsx
Labels: ready to merge

#25 Tmedia 658 component stack
  .storybook/theme.scss
  index.js
  scss.scss
  src/components/stack/_index.scss
  src/components/stack/index.jsx
  src/components/stack/index.stories.mdx
  src/components/stack/index.test.jsx
Labels: ready to merge
