Repository WPMedia/arc-themes-components, pull requests merged in 2022-03, with the labels that each got.

#28 TMEDIA-668: date component without formatting
  index.js
  scss.scss
  src/components/date/_index.scss
  src/components/date/index.jsx
  src/components/date/index.stories.mdx
  src/components/date/index.test.jsx
Labels: question, ready for review

#32 Paragraph Component Impl
  .storybook/theme.scss
  scss.scss
  src/components/paragraph/_index.scss
  src/components/paragraph/index.jsx
  src/components/paragraph/index.stories.mdx
  src/components/paragraph/index.test.jsx
Labels: needs changes

#34 TMEDIA-688 - Icon Component
  index.js
  scss.scss
  src/components/icon/_index.scss
  src/components/icon/icons/ArrowLeft.jsx
  src/components/icon/icons/ArrowRight.jsx
  src/components/icon/icons/ChevronDown.jsx
  src/components/icon/icons/ChevronLeft.jsx
  src/components/icon/icons/ChevronRight.jsx
  src/components/icon/icons/ChevronUp.jsx
  src/components/icon/icons/Close.jsx
  src/components/icon/icons/Envelope.jsx
  src/components/icon/icons/Facebook.jsx
  src/components/icon/icons/Fullscreen.jsx
  src/components/icon/icons/HamburgerMenu.jsx
  src/components/icon/icons/Helpers.js
  src/components/icon/icons/Instagram.jsx
  src/components/icon/icons/Link.jsx
  src/components/icon/icons/LinkedIn.jsx
  src/components/icon/icons/Medium.jsx
  src/components/icon/icons/Next.jsx
  src/components/icon/icons/Pause.jsx
  src/components/icon/icons/PauseCircle.jsx
  src/components/icon/icons/Pinterest.jsx
  src/components/icon/icons/Play.jsx
  src/components/icon/icons/Previous.jsx
  src/components/icon/icons/Print.jsx
  src/components/icon/icons/Reddit.jsx
  src/components/icon/icons/Rss.jsx
  src/components/icon/icons/Search.jsx
  src/components/icon/icons/Share.jsx
  src/components/icon/icons/Snapchat.jsx
  src/components/icon/icons/SoundCloud.jsx
  src/components/icon/icons/SoundOff.jsx
  src/components/icon/icons/SoundOn.jsx
  src/components/icon/icons/Tumblr.jsx
  src/components/icon/icons/Twitch.jsx
  src/components/icon/icons/Twitter.jsx
  src/components/icon/icons/User.jsx
  src/components/icon/icons/WhatsApp.jsx
  src/components/icon/icons/Youtube.jsx
  src/components/icon/icons/ZoomIn.jsx
  src/components/icon/icons/ZoomOut.jsx
  src/components/icon/icons/index.js
  src/components/icon/index.jsx
  src/components/icon/index.stories.mdx
  src/components/icon/index.test.jsx
Labels: ready for review

#36 TMEDIA-696 - Add Image component
  .storybook/main.js
  index.js
  resources/computer-user.jpeg
  scss.scss
  src/components/image/_index.scss
  src/components/image/index.jsx
  src/components/image/index.stories.mdx
  src/components/image/index.test.jsx
Labels: ready for review

#35 Tmedia 671 caption component
  .storybook/theme.scss
  index.js
  scss.scss
  src/components/caption/_index.scss
  src/components/caption/index.jsx
  src/components/caption/index.stories.mdx
  src/components/caption/index.test.jsx
  src/utils/format-credits/formatCredits.test.js
  src/utils/format-credits/index.js
  src/utils/format-credits/index.stories.mdx
Labels: ready for review

#41 GitHub - Pull Request Template
  .github/pull_request_template.md
Labels: ready for review

#40 Usage Updates, and IconGallery
  _templates/component/new/storybook-story.ejs.t
  src/components/icon/index.stories.mdx
  src/components/image/index.stories.mdx
  src/components/link/index.stories.mdx
  src/components/paragraph/index.stories.mdx
  src/components/stack/index.stories.mdx
Labels: ready for review

#42 Update Storybook & Fix Docs loading error
  .eslintrc.js
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  package-lock.json
  package.json
Labels: ready for review

#43 Fix duplicate CSS for secondary-reverse, add medium hooks
  src/components/button/_index.scss
  src/components/button/index.jsx
Labels: ready for review

#44 TMEDIA-674: Attribution Component
  index.js
  scss.scss
  src/components/attribution/_index.scss
  src/components/attribution/index.jsx
  src/components/attribution/index.stories.mdx
  src/components/attribution/index.test.jsx
Labels: ready to merge

#45 TMEDIA 687 separator
  index.js
  scss.scss
  src/components/paragraph/_index.scss
  src/components/separator/_index.scss
  src/components/separator/index.jsx
  src/components/separator/index.stories.mdx
  src/components/separator/index.test.jsx
  src/scss/root/_index.scss
Labels: ready for review

#46 TMEDIA 685 Pill
  index.js
  scss.scss
  src/components/overline/_index.scss
  src/components/pill/_index.scss
  src/components/pill/index.jsx
  src/components/pill/index.stories.mdx
  src/components/pill/index.test.jsx
Labels: ready to merge

#48 Tmedia 676 input component
  index.js
  scss.scss
  src/components/input/_index.scss
  src/components/input/index.jsx
  src/components/input/index.stories.mdx
  src/components/input/index.test.jsx
Labels: ready to merge

#54 TMEDIA-768 - Theme Switcher
  .storybook/main.js
  .storybook/preview.js
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
  package-lock.json
  package.json
Labels: ready for review

#56 Update Reset for Media Items, Bold and Italic
  src/scss/root/_reset.scss
Labels: ready to merge

#53 TMEDIA-709 - video player
  .storybook/preview-head.html
  .storybook/themes/news.scss
  index.js
  package-lock.json
  package.json
  scss.scss
  src/components/video/_index.scss
  src/components/video/index.jsx
  src/components/video/index.stories.mdx
  src/components/video/index.test.jsx
  src/utils/format-powa-video-embed/formatPowaVideoEmbed.test.js
  src/utils/format-powa-video-embed/index.js
  src/utils/format-powa-video-embed/index.stories.mdx
Labels: ready for review

#58 Add assistiveHidden prop to button
  src/components/button/index.jsx
  src/components/button/index.test.jsx
Labels: ready for review

#60 Sass library updates for block components per breakpoint
  src/scss/index.test.scss
  src/scss/root/_index.scss
Labels: ready for review

#59 Update components to allow consumer to use all HTML attributes
  _templates/component/new/default-entry.ejs.t
  _templates/component/new/test.ejs.t
  src/components/attribution/index.jsx
  src/components/attribution/index.test.jsx
  src/components/date/index.jsx
  src/components/date/index.test.jsx
  src/components/headings/heading/index.jsx
  src/components/headings/index.test.jsx
  src/components/icon/index.jsx
  src/components/icon/index.test.jsx
  src/components/input/index.test.jsx
  src/components/link/index.jsx
  src/components/link/index.test.jsx
  src/components/media-item/index.jsx
  src/components/media-item/index.test.jsx
  src/components/overline/index.jsx
  src/components/overline/index.test.jsx
  src/components/paragraph/index.jsx
  src/components/paragraph/index.test.jsx
  src/components/pill/index.jsx
  src/components/pill/index.test.jsx
  src/components/separator/index.jsx
  src/components/separator/index.test.jsx
  src/components/stack/index.jsx
  src/components/stack/index.test.jsx
  src/components/video/index.jsx
  src/components/video/index.test.jsx
Labels: ready for review
