Repository WPMedia/arc-themes-components, pull requests merged in 2023-11, with the labels that each got.

#216 Updated Twitter icon to X
  src/components/icon/icons/Twitter.jsx
Labels: ready to merge

#218 Themes 1480: Enable tests (with reduced coverage constraints for now)
  .eslintrc.js
  __tests__/scss.test.js
  jest.config.js
  package-lock.json
  package.json
  src/components/details/index.test.jsx
  src/components/meta-data/index.test.jsx
  src/components/paragraph/index.test.jsx
  src/utils/format-powa-video-embed/index.test.js
Labels: ready to merge

#217 THEMES-1474: Input display bug
  src/components/input/themes/commerce.json
  src/components/input/themes/news.json
Labels: do not merge

#212 DAM-7996
  scripts/style-token-descriptions.json
  src/components/conditional/index.stories.mdx
  src/components/media-item/STYLE-TOKENS.md
  src/components/media-item/_index.scss
  src/components/media-item/index.stories.mdx
  src/components/media-item/themes/commerce.json
  src/components/media-item/themes/news.json
  src/components/video/STYLE-TOKENS.md
  src/components/video/_index.scss
  src/components/video/index.jsx
  src/components/video/index.stories.mdx
  src/components/video/index.test.jsx
  src/components/video/themes/commerce.json
  src/components/video/themes/news.json
  src/utils/format-powa-video-embed/index.js
  src/utils/get-powa-aspect-ratio/index.js
  src/utils/get-powa-aspect-ratio/index.test.js
Labels: additional review, ready for review

#219 THEMES-1476: Dropdown input
  src/components/input/STYLE-TOKENS.md
  src/components/input/_index.scss
  src/components/input/index.jsx
  src/components/input/index.stories.mdx
  src/components/input/index.test.jsx
  src/components/input/themes/commerce.json
  src/components/input/themes/news.json
Labels: ready for review

#221 THEMES-1538: Move useIdentity hook
  index.js
  package-lock.json
  package.json
  src/utils/hooks/use-identity/index.js
  src/utils/hooks/use-identity/index.test.js
Labels: ready for review

#222 THEMES-1486: Add icons to component library
  src/components/icon/icons/Check.jsx
  src/components/icon/icons/Google.jsx
  src/components/icon/icons/GoogleColor.jsx
  src/components/icon/icons/TikTok.jsx
  src/components/icon/icons/TikTokColor.jsx
  src/components/icon/icons/index.js
  src/components/icon/index.jsx
Labels: ready for review
