Repository WPMedia/arc-themes-components, pull requests merged in 2023-12, with the labels that each got.

#225 Update .browserslistrc
  .browserslistrc
Labels: ready for review

#228 THEMES-1400: Resizer URL bug
  src/components/image/index.test.jsx
  src/utils/image-ans-to-image-src/index.js
  src/utils/image-ans-to-image-src/index.test.js
Labels: ready for review

#226 added text direction variable
  src/scss/root/_index.scss
Labels: ready for review

#227 THEMES-1221: Update carousel styles
  .eslintrc.js
  .storybook/themes/news.scss
  .stylelintrc.json
  package-lock.json
  package.json
  src/components/carousel/_index.scss
  src/components/carousel/index.stories.mdx
  src/components/carousel/themes/commerce.json
  src/components/carousel/themes/news.json
  src/components/paragraph/_index.scss
  src/utils/hooks/use-identity/index.test.jsx
Labels: ready to merge

#229 Lint Updates
  .browserslistrc
  .eslintrc.js
  .husky/pre-commit
  .husky/pre-push
  .stylelintrc.json
  package-lock.json
  package.json
  src/components/paragraph/_index.scss
  src/scss/root/_index.scss
Labels: review in progress

#233 Updating 2.1.3 with changes from 2.1.2
  src/components/image/index.test.jsx
  src/components/meta-data/index.jsx
  src/utils/image-ans-to-image-src/index.js
  src/utils/image-ans-to-image-src/index.test.js
Labels: ready for review, ready to merge

#231 THEMES-1228: Replace @wpmedia/timezone
  debugging-timezone-postinstall-dates.md
  package.json
  scripts/postinstall.js
  src/utils/localize-date/helper.js
  src/utils/localize-date/index.js
  src/utils/localize-date/index.test.js
Labels: ready for review

#234 added back text direction logic
  src/scss/root/_index.scss
Labels: ready for review
