Repository WPMedia/arc-themes-components, pull requests merged in 2023-07, with the labels that each got.

#191 Themes 1198 social share bar hover styles
  package-lock.json
  src/components/icon/_index.scss
Labels: ready for review

#192 THEMES-1173: header nav | Update button component to match new design
  .storybook/themes/news.scss
  src/components/button/themes/news.json
Labels: ready to merge

#195 THEMES 1198.5 social icons redux
  src/components/icon/_index.scss
Labels: do not merge

#197 Added overline font-family
  src/components/overline/themes/commerce.json
  src/components/overline/themes/news.json
Labels: ready for review

#199 updated link color and font-family
  src/components/link/themes/news.json
Labels: ready to merge
