Repository WPMedia/arc-themes-components, pull requests merged in 2023-08, with the labels that each got.

#201 Themes 1289 V2 Video Center | Arc block - video needs to resize to handle the correct size when we have vertical video
  index.js
  src/components/video/index.jsx
  src/utils/get-aspect-ratio/index.js
  src/utils/get-aspect-ratio/index.test.js
Labels: ready for review

#206 THEMES 1350 V2 Video Center | Arc block - Remove the black bars from the vertical video in mobile view.
  .storybook/themes/commerce.scss
  .storybook/themes/news.scss
  src/components/video/themes/commerce.json
  src/components/video/themes/news.json
Labels: design qa

#205 THEMES-1280 Gallery + Lead Art (mobile) | Update autoplay, progress indicator, carousel, and close controls in focus (expand) view
  .storybook/themes/news.scss
  src/components/carousel/_index.scss
  src/components/carousel/themes/news.json
Labels: ready to merge
