Repository WPMedia/arc-themes-components, pull requests merged in 2024-05, with the labels that each got.

#258 THEMES-1904: Linting fixes for components
  .github/workflows/pull-requests-test-and-lint.yml
  .stylelintrc.json
  jest.config.js
  src/components/attribution/_index.scss
  src/components/attribution/index.test.jsx
  src/components/badge/index.test.jsx
  src/components/bot-challenge-protection/_index.scss
  src/components/bot-challenge-protection/index.jsx
  src/components/button/_index.scss
  src/components/carousel/_children/DotIndicatorArea.test.jsx
  src/components/carousel/_children/Item.test.jsx
  src/components/carousel/_index.scss
  src/components/details/_index.scss
  src/components/grid/_index.scss
  src/components/headings/_index.scss
  src/components/input/_index.scss
  src/components/input/index.jsx
  src/components/input/index.test.jsx
  src/components/media-item/_index.scss
  src/components/paragraph/_index.scss
  src/components/separator/_index.scss
  src/components/stack/_index.scss
  src/components/video/_index.scss
  src/scss/root/_a11y.scss
Labels: ready for review

#261 Subscriptions - payment brands credit/debit card
  src/components/icon/icons/Amex.jsx
  src/components/icon/icons/ApplePay.jsx
  src/components/icon/icons/Diners.jsx
  src/components/icon/icons/Discover.jsx
  src/components/icon/icons/GooglePay.jsx
  src/components/icon/icons/Jcb.jsx
  src/components/icon/icons/Mastercard.jsx
  src/components/icon/icons/PayPal.jsx
  src/components/icon/icons/Unionpay.jsx
  src/components/icon/icons/Visa.jsx
  src/components/icon/icons/index.js
  src/components/icon/index.jsx
Labels: ready for review

#259 ASUB-7972 Radio button
  src/components/bot-challenge-protection/index.jsx
  src/components/input/_index.scss
  src/components/input/index.jsx
  src/components/input/index.test.jsx
  src/components/input/themes/news.json
  src/components/stack/_index.scss
  src/components/stack/index.jsx
Labels: ready to merge

#266 THEMES-1916: Add Additional author object image type
  src/utils/sign-images-in-ans-object/index.js
  src/utils/sign-images-in-ans-object/index.test.js
Labels: ready for review

#267 Re-added null value check
  src/utils/sign-images-in-ans-object/index.js
  src/utils/sign-images-in-ans-object/index.test.js
Labels: ready for review, review in progress
